# Discord OATH token - https://discordapp.com/developers/docs/topics/oauth2
dbot_access_token = ""

command_prefix = "!"

# Directory to store plugins in.
plugins_dir = "./plugins"

# Text to be desplayed for the '!about' command.
about_message = """
DBot - A Discord bot framework by Bryan Cuneo
https://github.com/BryanCuneo/dbot"""
